# Generated by Django 3.0.2 on 2020-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(default='testing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_creator',
            field=models.CharField(default='testing', max_length=100),
            preserve_default=False,
        ),
    ]
