# Generated by Django 3.0.2 on 2020-05-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_project_project_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_notes',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
    ]
